#!/usr/bin/env python3
"""Static site generator for Abdallah Yaackoubi's portfolio.

Reads site.json, tokens.json and projects/*/content.json, then writes plain
HTML to disk. There is no runtime data fetching: fetch() is blocked on
file:// in Chrome, so everything is baked in at build time.

    python3 build.py

Outputs index.html, about.html, projects/<slug>.html and assets/tokens.css.
"""

import html
import json
import os
import re
import struct
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
SITE = json.loads((ROOT / "site.json").read_text(encoding="utf-8"))
TOKENS = json.loads((ROOT / "tokens.json").read_text(encoding="utf-8"))

# Fields rendered in the facts table, in order.
FACTS = ["role", "client", "year", "duration", "team", "status"]
LIST_FACTS = [("platforms", "Platforms"), ("tools", "Tools")]


# ─────────────────────────────────────────── helpers

def e(text):
    """Escape for HTML text/attribute context."""
    return html.escape(str(text if text is not None else ""), quote=True)


def is_todo(value):
    """BUILD.md: skip any field whose value starts with TODO."""
    return isinstance(value, str) and value.strip().startswith("TODO")


def usable(value):
    return bool(value) and not is_todo(value)


def png_size(path):
    """Intrinsic size of a PNG or JPEG, so <img> can reserve space.

    Named for PNG because that was all the export produced, but the
    portrait is a JPEG and every <img> must carry width/height or the
    page reflows as images load.
    """
    try:
        with open(path, "rb") as fh:
            head = fh.read(24)
            if head[:8] == b"\x89PNG\r\n\x1a\n":
                return struct.unpack(">II", head[16:24])
            if head[:2] == b"\xff\xd8":                 # JPEG: walk to a SOF marker
                fh.seek(2)
                while True:
                    byte = fh.read(1)
                    while byte and byte != b"\xff":
                        byte = fh.read(1)
                    if not byte:
                        return None
                    marker = fh.read(1)
                    while marker == b"\xff":
                        marker = fh.read(1)
                    if not marker:
                        return None
                    if marker[0] in (0xC0, 0xC1, 0xC2, 0xC3):
                        fh.read(3)
                        height, width = struct.unpack(">HH", fh.read(4))
                        return width, height
                    length = struct.unpack(">H", fh.read(2))[0]
                    fh.seek(length - 2, 1)
    except (OSError, struct.error):
        pass
    return None


def masked(text):
    """Wrap text so it can slide up from behind a mask.

    The outer span clips; the inner one is what moves. Used on the oversized
    headings only — at that scale a whole-line reveal reads far better than
    a per-character stagger.
    """
    return '<span class="mask"><span class="mask__in">%s</span></span>' % e(text)


def paragraphs(body):
    """Split a body string into <p> blocks on blank lines."""
    out = []
    for chunk in re.split(r"\n\s*\n", (body or "").strip()):
        chunk = chunk.strip()
        if chunk:
            out.append("<p>%s</p>" % e(chunk).replace("\n", "<br>"))
    return "\n        ".join(out)


def load_projects():
    projects = []
    for folder in sorted((ROOT / "projects").iterdir()):
        cfg = folder / "content.json"
        if cfg.is_file():
            data = json.loads(cfg.read_text(encoding="utf-8"))
            data["_dir"] = folder.name          # e.g. "01-steer"
            projects.append(data)
    projects.sort(key=lambda p: p.get("order", 999))
    return projects


def by_slug(projects):
    return {p["slug"]: p for p in projects}


# ─────────────────────────────────────────── tokens → css

def flatten_tokens(tokens):
    """tokens.json → CSS custom properties.

    color.bgAlt      -> --color-bg-alt
    fontSize.2xl     -> --font-size-2xl
    layout.proseWidth-> --prose-width      (layout keys are un-prefixed)
    """
    alias = {"layout": ""}
    lines = []
    for group, values in tokens.items():
        if group.startswith("_") or not isinstance(values, dict):
            continue
        prefix = alias.get(group, group)
        prefix = re.sub(r"(?<!^)(?=[A-Z])", "-", prefix).lower()
        for key, value in values.items():
            name = re.sub(r"(?<!^)(?=[A-Z])", "-", str(key)).lower()
            var = "--%s-%s" % (prefix, name) if prefix else "--%s" % name
            lines.append("  %s: %s;" % (var, value))
    return lines


def write_tokens_css():
    """tokens.json is the single source of truth; this file is derived.

    The palette is dark by design rather than via prefers-color-scheme, so
    there is no second colour set to keep in sync. A light override could be
    added here later without touching styles.css.
    """
    body = "\n".join(flatten_tokens(TOKENS))
    css = (
        "/* GENERATED by build.py from tokens.json — do not edit by hand. */\n"
        ":root {\n%s\n  color-scheme: dark;\n}\n" % body
    )
    (ROOT / "assets").mkdir(exist_ok=True)
    (ROOT / "assets" / "tokens.css").write_text(css, encoding="utf-8")
    return css.count("--")


# ─────────────────────────────────────────── page chrome

def head(title, description, *, depth=0, image=None, page_url=""):
    up = "../" * depth
    og_image = ('\n  <meta property="og:image" content="%s">' % e(image)) if image else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(title)}</title>
  <meta name="description" content="{e(description)}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(description)}">{og_image}
  <link rel="stylesheet" href="{up}assets/fonts.css">
  <link rel="stylesheet" href="{up}assets/tokens.css">
  <link rel="stylesheet" href="{up}assets/styles.css">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-head">
    <div class="shell site-head__inner">
      <a class="site-head__name" href="{up}index.html">{e(SITE['name'])}</a>
      <nav aria-label="Primary">
        <a href="{up}index.html#work">Work</a>
        <a href="{up}about.html">About</a>
        <a href="mailto:{e(SITE['email'])}">Contact</a>
      </nav>
    </div>
  </header>
  <main id="main">"""


def foot(depth=0):
    up = "../" * depth
    links = "\n        ".join(
        '<a href="%s">%s</a>' % (e(l["url"]), e(l["label"])) for l in SITE.get("links", [])
    )
    return f"""  </main>
  <footer class="site-foot">
    <div class="shell site-foot__inner">
      <p class="site-foot__note">© 2026 {e(SITE['name'])}</p>
      <nav class="site-foot__links" aria-label="Elsewhere">
        {links}
        <a href="{up}{e(SITE['cv'])}">CV</a>
      </nav>
    </div>
  </footer>
  <script src="{up}assets/lightbox.js" defer></script>
  <script src="{up}assets/enhance.js" defer></script>
</body>
</html>
"""


# ─────────────────────────────────────────── fragments

def figure(img, project_dir, depth):
    """One <figure>. depth is how many folders deep the page sits."""
    src = "%s/%s" % (project_dir, img["src"]) if depth else "projects/%s/%s" % (project_dir, img["src"])
    disk = ROOT / "projects" / project_dir / img["src"]
    size = png_size(disk)
    dims = ' width="%d" height="%d"' % size if size else ""
    # Very tall exports (4000px+) get capped in CSS and opened via the lightbox.
    tall = ' data-tall="true"' if size and size[1] > 2200 else ""
    caption = img.get("caption")
    cap_html = "\n          <figcaption>%s</figcaption>" % e(caption) if caption else ""
    bleed = "" if tall else " shot--bleed"
    return f"""        <figure class="shot{bleed}"{tall}>
          <button class="shot__btn" type="button" data-full="{e(src)}" aria-label="Open full image: {e(img.get('alt',''))}">
            <img src="{e(src)}" alt="{e(img.get('alt',''))}"{dims} loading="lazy" decoding="async">
          </button>{cap_html}
        </figure>"""


def project_card(project, *, large):
    cover = "projects/%s/%s" % (project["_dir"], project["cover"])
    size = png_size(ROOT / "projects" / project["_dir"] / project["cover"])
    dims = ' width="%d" height="%d"' % size if size else ""
    cls = "card card--lg" if large else "card"
    num = "%02d" % project.get("order", 0)
    return f"""        <li>
          <a class="{cls}" href="projects/{e(project['slug'])}.html">
            <span class="card__media">
              <span class="card__num" aria-hidden="true">{num}</span>
              <img src="{e(cover)}" alt="{e(project['title'])} cover" {dims} loading="lazy" decoding="async">
            </span>
            <span class="card__body">
              <span class="card__title">{e(project['title'])}</span>
              <span class="card__tagline">{e(project['tagline'])}</span>
            </span>
          </a>
        </li>"""


# ─────────────────────────────────────────── pages

def build_index(projects):
    slugs = by_slug(projects)
    out = [head(
        "%s — %s" % (SITE["name"], SITE["title"]),
        SITE["tagline"] + " " + SITE["intro"],
        image="site/profile.png",
    )]

    # Cycling role line. Every role is in the DOM so it survives with JS off
    # and is indexable; JS reveals one at a time. The live list is aria-hidden
    # and a static label carries the accessible name, so assistive tech reads
    # the role once instead of announcing every swap.
    roles = [r for r in SITE.get("roles", []) if r] or [SITE["title"]]
    items = "".join(
        '<span class="roles__item%s">%s</span>' % (" is-on" if i == 0 else "", e(r))
        for i, r in enumerate(roles))
    # The h1 must still say who this is even though the name is not shown
    # here, so the accessible text carries name + every role while the
    # animated list is hidden from assistive tech.
    roles_html = (
        '<h1 class="hero__lead">'
        '<span class="visually-hidden">%s — %s</span>'
        '<span class="roles" data-roles aria-hidden="true">%s</span>'
        '</h1>' % (e(SITE["name"]), e(", ".join(roles)), items))

    hero_img = SITE.get("heroImage") or SITE["profileImage"]
    psize = png_size(ROOT / hero_img)
    pdims = ' width="%d" height="%d"' % psize if psize else ""
    out.append(f"""
    <section class="hero shell">
      <div class="hero__text">
        {roles_html}
        <p class="hero__tagline">{e(SITE['tagline'])}</p>
        <p class="hero__intro">{e(SITE['intro'])}</p>
      </div>
      <figure class="hero__portrait">
        <img src="{e(hero_img)}" alt="Portrait of {e(SITE['name'])}"{pdims} decoding="async">
      </figure>
    </section>
""")

    for key, large in (("caseStudies", True), ("otherProjects", False)):
        meta = SITE["sections"][key]
        anchor = ' id="work"' if key == "caseStudies" else ""
        cards = "\n".join(
            project_card(slugs[s], large=large) for s in meta["slugs"] if s in slugs
        )
        out.append(f"""
    <section class="band shell"{anchor}>
      <div class="band__head">
        <h2>{masked(meta['heading'])}</h2>
        <p>{e(meta['description'])}</p>
      </div>
      <ul class="grid {'grid--lg' if large else 'grid--sm'}" style="--cols: {2 if large else 4}">
{cards}
      </ul>
    </section>
""")

    contact_links = "\n        ".join(
        '<a class="btn" href="%s">%s</a>' % (e(l["url"]), e(l["label"])) for l in SITE["links"]
    )
    out.append(f"""
    <section class="band band--contact shell" id="contact">
      <h2>{masked("Let's talk")}</h2>
      <p class="lede">Open to freelance and full-time product design work.</p>
      <div class="btn-row">
        {contact_links}
      </div>
    </section>
""")
    out.append(foot())
    (ROOT / "index.html").write_text("\n".join(out), encoding="utf-8")


def build_about():
    body = "\n      ".join("<p>%s</p>" % e(p) for p in SITE["about"])
    links = "\n        ".join(
        '<a class="btn" href="%s">%s</a>' % (e(l["url"]), e(l["label"])) for l in SITE["links"]
    )
    size = png_size(ROOT / SITE["profileImage"])
    dims = ' width="%d" height="%d"' % size if size else ""
    out = [head("About — %s" % SITE["name"], SITE["intro"], image=SITE["profileImage"])]
    out.append(f"""
    <article class="shell about">
      <h1>{masked("About")}</h1>
      <div class="about__grid">
        <figure class="about__portrait">
          <img src="{e(SITE['profileImage'])}" alt="Portrait of {e(SITE['name'])}"{dims} decoding="async">
        </figure>
        <div class="prose">
          {body}
          <p class="about__cta">
            <a class="btn btn--solid" href="{e(SITE['cv'])}">Download CV (PDF)</a>
          </p>
          <div class="btn-row">
        {links}
          </div>
        </div>
      </div>
    </article>
""")
    out.append(foot())
    (ROOT / "about.html").write_text("\n".join(out), encoding="utf-8")


def build_project(project, prev_p, next_p):
    d = project["_dir"]
    out = [head(
        "%s — %s" % (project["title"], SITE["name"]),
        project["summary"],
        depth=1,
        image="../projects/%s/%s" % (d, project["cover"]),
    )]

    facts = "".join(
        "<div class=\"facts__row\"><dt>%s</dt><dd>%s</dd></div>" % (e(f.capitalize()), e(project[f]))
        for f in FACTS if usable(project.get(f))
    )
    for key, label in LIST_FACTS:
        if project.get(key):
            facts += "<div class=\"facts__row\"><dt>%s</dt><dd>%s</dd></div>" % (
                e(label), e(", ".join(project[key])))
    facts_html = '<dl class="facts">%s</dl>' % facts if facts else ""

    metrics_html = ""
    if project.get("metrics"):
        cells = "".join(
            '<div class="metric"><span class="metric__value">%s</span>'
            '<span class="metric__label">%s</span></div>' % (e(m["value"]), e(m["label"]))
            for m in project["metrics"]
        )
        metrics_html = '<div class="metrics">%s</div>' % cells

    links_html = ""
    if project.get("links"):
        items = "".join(
            '<a class="btn" href="%s" rel="noopener">%s</a>' % (e(l["url"]), e(l["label"]))
            for l in project["links"]
        )
        links_html = '<div class="btn-row">%s</div>' % items

    tags_html = ""
    if project.get("tags"):
        tags_html = '<ul class="tags">%s</ul>' % "".join(
            "<li>%s</li>" % e(t) for t in project["tags"])

    # Asymmetric header: narrative on the left, facts pinned on the right.
    toc_html = ""
    toc_items = [sec for sec in project.get("sections", []) if sec.get("id")]
    if len(toc_items) > 2:
        rows = "".join(
            '<li><a href="#%s">%s</a></li>' % (e(sec["id"]), e(sec["heading"]))
            for sec in toc_items)
        toc_html = ('<nav class="toc" aria-label="On this page">'
                    '<p class="toc__label">On this page</p>'
                    '<ol class="toc__list">%s</ol></nav>' % rows)

    out.append(f"""
    <article class="project">
      <div class="progress" aria-hidden="true"><span class="progress__bar"></span></div>
      <header class="shell project__head">
        <div class="project__intro">
          <p class="eyebrow">{e('Case study' if project['category'] == 'case-study' else 'Project')}</p>
          <h1>{masked(project['title'])}</h1>
          <p class="project__tagline">{e(project['tagline'])}</p>
          <p class="prose project__summary">{e(project['summary'])}</p>
          {tags_html}
          {metrics_html}
          {links_html}
        </div>
        <aside class="project__meta">
          {toc_html}
          {facts_html}
        </aside>
      </header>
""")

    for section in project.get("sections", []):
        figs = "\n".join(figure(img, d, depth=1) for img in section.get("images", []))
        figs_html = '\n      <div class="shots">\n%s\n      </div>' % figs if figs else ""
        out.append(f"""
      <section class="shell project__section" id="{e(section.get('id',''))}">
        <h2>{e(section['heading'])}</h2>
        <div class="prose">
        {paragraphs(section.get('body'))}
        </div>
      </section>{figs_html}
""")

    nav = []
    if prev_p:
        nav.append('<a class="pager__link pager__link--prev" href="%s.html">'
                   '<span>Previous</span><strong>%s</strong></a>'
                   % (e(prev_p["slug"]), e(prev_p["title"])))
    if next_p:
        nav.append('<a class="pager__link pager__link--next" href="%s.html">'
                   '<span>Next project</span><strong>%s</strong></a>'
                   % (e(next_p["slug"]), e(next_p["title"])))
    out.append("""
      <nav class="shell pager" aria-label="More projects">
        %s
      </nav>
    </article>
""" % "\n        ".join(nav))

    out.append(foot(depth=1))
    (ROOT / "projects" / ("%s.html" % project["slug"])).write_text(
        "\n".join(out), encoding="utf-8")


# ─────────────────────────────────────────── main

def main():
    projects = load_projects()
    n_vars = write_tokens_css()
    build_index(projects)
    build_about()
    for i, p in enumerate(projects):
        build_project(p, projects[i - 1] if i else None,
                      projects[i + 1] if i + 1 < len(projects) else None)

    imgs = sum(len(s.get("images", [])) for p in projects for s in p.get("sections", []))
    print("tokens.css   %d custom properties" % n_vars)
    print("index.html   %d case studies, %d other projects"
          % (len(SITE["sections"]["caseStudies"]["slugs"]),
             len(SITE["sections"]["otherProjects"]["slugs"])))
    print("about.html   %d paragraphs" % len(SITE["about"]))
    print("projects/    %d pages, %d figures" % (len(projects), imgs))


if __name__ == "__main__":
    main()
